name: VIPCredits
version: ${project.version}
main: com.gabrielhd.credits.Main
author: GabrielHD55
description: Simple Credits system
api-version: 1.13
softdepend:
  - PlaceholderAPI
commands:
  creditos:
    usage: /<command>
    aliases:
      - points
      - credits
      - pontos